### ISSUE TITLE
Check PubMed Loader Working

### ISSUE THREAD

**Issue by cannin** [cannin/gsoc_2024_cbioportal_chatbot#12]
You should be able to pass in the PMIDs from the studies API: "https://www.cbioportal.org/api/swagger-ui/index.html#/Studies/getAllStudiesUsingGET" and get the abstract text to generate embeddings

**Comment by XinlingWang0628** [comment]
switch to PMC loader

**Comment by XinlingWang0628** [comment]
add a commit of isolating parsing logic, unit test, and function description in previous PR.

**Comment by XinlingWang0628** [comment]
Done.
<img width="1264" alt="Screenshot 2024-08-30 at 2 45 22 PM" src="https://github.com/user-attachments/assets/f0f43a81-3d70-424a-9998-aced6fb38a12">
