### ISSUE TITLE
Modify PubmedLoader to work with PubMedCentral

### ISSUE THREAD

**Issue by cannin** [cannin/gsoc_2024_cbioportal_chatbot#13]
Modify the loader to work with PMC. 

# Example URL
https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pmc&id=PMC3898398&retmode=xml

# Use code from here to extract the text: extract_text() 
https://gist.github.com/cannin/f4c1c21926a21f8a38de577ca2f0fc4c

**Comment by XinlingWang0628** [comment]
There 65 studies don't have pmid.
[no_pmid_list.json](https://github.com/user-attachments/files/15827411/no_pmid_list.json)

**Comment by cannin** [comment]
Out of how many? You still have many and should proceed with those.

**Comment by XinlingWang0628** [comment]
65 out of 411.

**Comment by XinlingWang0628** [comment]
So far, I loaded 250 pubmed papers using xml loader. I found there are 40 studies have no pmcid, and 28 studies have pmcid but no xml. Do you have any questions to ask chatbot about pubmed papers, this can help me to check the accuracy and make some change if needed.

**Comment by XinlingWang0628** [comment]
I found there are 18 studies have same pmid list, and I am not sure if these pmid data is correct or not.  Also, some of pmids in the list appeared 32 times or more. The pmid list is : "29625048,29596782,29622463,29617662,29625055,29625050,29617662,30643250,32214244,29625049,29850653".
<img width="916" alt="Screenshot 2024-06-19 at 4 36 56 PM" src="https://github.com/cannin/gsoc_2024_cbioportal_chatbot/assets/105673895/374d2d84-55cf-40e3-83d4-db5be203520c">

**Comment by cannin** [comment]
A simple question to verify would be how many samples in study X? This could come from LangChain OpenAPI or the publication.

**Comment by XinlingWang0628** [comment]
Hi Augustin, I found pmid for those 5 studies missing pmid, but I am not sure about this pmid, could you please help me to double check when you are available?  
{ "name": "Gastrointestinal Stromal Tumors (MSK, Clin Cancer Res 2023)",
  "description": "Targeted sequencing of 469 gastrointestinal stromal tumors and their matched normals via MSK-IMPACT.",
  "publicStudy": true,
  "pmid": "36971786",
  "groups": "",
  "status": 0,
  "importDate": "2023-12-07 18:44:10",
  "allSampleCount": 469,
  "readPermission": true,
  "studyId": "gist_msk_2023",
  "cancerTypeId": "gist",
  "referenceGenome": "hg19"}.

**Comment by cannin** [comment]
I think the PMID is wrong. Probably this one: https://pubmed.ncbi.nlm.nih.gov/37477937/ (talk with Ruslan about fixing it; not the highest priority).

**Comment by XinlingWang0628** [comment]
Got it, thank you. I am working on testing pubmed chatbot and its pdf loader.
