### ISSUE TITLE
Dockerfile for Project

### ISSUE THREAD

**Issue by cannin** [cannin/gsoc_2024_cbioportal_chatbot#15]
Make a Dockerfile and test the resulting Docker image for the project
https://medium.com/@anshita.bhasin/a-step-by-step-guide-to-create-dockerfile-9e3744d38d11

**Comment by XinlingWang0628** [comment]
Done, https://hub.docker.com/r/xinlingwang/docker-project-repo

**Comment by XinlingWang0628** [comment]
Docker: https://hub.docker.com/repository/docker/xinlingwang/chatbot/general 
To run: docker run -p 7860:7860 cbio_chatbot_gradio_new

**Comment by cannin** [comment]
Real command is: docker run -p 7860:7860 xinlingwang/chatbot

**Comment by XinlingWang0628** [comment]
Combined chatbot in docker file: https://hub.docker.com/repository/docker/xinlingwang/gsoc_chatbot/general   
To run: docker run -p 7860:7860 --env-file .env xinlingwang/gsoc_chatbot:combined
