### ISSUE TITLE
train chatbot to make plots

### ISSUE THREAD

**Issue by XinlingWang0628** [cannin/gsoc_2024_cbioportal_chatbot#21]
Use the example in line[22] from https://github.com/mskcc/cbsp-hackathon/blob/master/0-introduction/cbsp_hackathon.ipynb 
Train the chatbot to make different plots.

Results: chatbot provided code for bar_chart, pie_chart, and scatter_chart. 

![pie chart](https://github.com/user-attachments/assets/5db84681-7d1a-4ad5-af51-6226c722d6c5)

![scatter chart](https://github.com/user-attachments/assets/b598e8ee-811d-46bb-aa27-4fda9540e89f)
50c7-4fa3-bd35-cec0922ce2ad)
![bar_plot](https://github.com/user-attachments/assets/3dd66376-95a8-472c-b748-38315cdcaeba)

**Comment by cannin** [comment]
Make a Jupyter notebook. For each image, I want to see:

* Chatbot question 
* Chatbot answer 
* Chatbot code
* Original image
* Image from Chatbot after running generated code

I guess you have to do this manually

**Comment by XinlingWang0628** [comment]
need a link

**Comment by XinlingWang0628** [comment]
combine plot chain with openapi to get study info and sample info. Example question: "can u write code about making a pie chart of number of samples in SCLC studies"

**Comment by XinlingWang0628** [comment]
show the everything (openapi response )in plot_chain

**Comment by XinlingWang0628** [comment]
combined this chain into cBioportal chatbot

**Comment by XinlingWang0628** [comment]
Passed the openapi response to plot_chain. Chatbot response includes study data and code to make a plot. 
chat history:
[chat_history (28).txt](https://github.com/user-attachments/files/16803838/chat_history.28.txt)
Jupyter notebook link for chatbot res: https://github.com/cannin/gsoc_2024_cbioportal_chatbot/blob/main/plot_for_sclc.ipynb
