### ISSUE TITLE
Add Conversation Download Button

### ISSUE THREAD

**Issue by cannin** [cannin/gsoc_2024_cbioportal_chatbot#23]

**Comment by XinlingWang0628** [comment]
Done. The issue before was caused by gradio downloadButton bug. I create a download button myself in html. 
<img width="1297" alt="Screenshot 2024-08-26 at 3 10 37 PM" src="https://github.com/user-attachments/assets/bfe336d8-d1a8-4cca-a886-5fd0da2787af">
