### ISSUE TITLE
Add Disclaimer text

### ISSUE THREAD

**Issue by cannin** [cannin/gsoc_2024_cbioportal_chatbot#24]
Same as ChatGPT add: "This chatbot can make mistakes. Check important info." in footer

**Comment by XinlingWang0628** [comment]
Done

**Comment by XinlingWang0628** [comment]
<img width="1336" alt="Screenshot 2024-08-21 at 5 34 42 PM" src="https://github.com/user-attachments/assets/666e9179-6817-4d42-891a-89adcdc97745">

Used gradio chatbot_interface, so cannot modify its footer, but can add html. So I add disclaimer as a new footer.
