### ISSUE TITLE
Missing Links to Source Document

### ISSUE THREAD

**Issue by cannin** [cannin/gsoc_2024_cbioportal_chatbot#26]
There's no link to the source document. At a minimum, implement this for the documentation.

<img width="1235" alt="Screenshot 2024-08-16 at 1 40 33 PM" src="https://github.com/user-attachments/assets/cf862f16-897d-438b-9288-1a45652582d6">

In the metadata can you not include the 1) documentation file path or 2) the URL of the mbox message (https://groups.google.com/g/cbioportal/c/UYkA14XPP6o) and then include in response to users?

**Comment by XinlingWang0628** [comment]
Fixed. 
<img width="1237" alt="Screenshot 2024-08-16 at 1 50 31 PM" src="https://github.com/user-attachments/assets/14f1fb54-9863-4cf0-8e2d-c809957c822c">

**Comment by XinlingWang0628** [comment]
updated chatbot link: https://4e8da0437711d39efb.gradio.live

**Comment by cannin** [comment]
@XinlingWang0628 move disclaimer text

<img width="1464" alt="Screenshot 2024-08-16 at 1 56 42 PM" src="https://github.com/user-attachments/assets/2d874aa3-d9af-4931-a20c-6c99841a271e">

**Comment by XinlingWang0628** [comment]
Responses for documentation questions contain source document URL : 

Example one: 
> Question: Can u please introduce cbioportal 
> Source Document Type : documentation
> Based on the provided contexts, cBioPortal is an online platform designed for the comprehensive visualization and analysis of cancer genomic data. It serves as a valuable resource for researchers and clinicians interested in exploring the genetic alterations across various cancer types. The platform offers a suite of interactive tools that enable users to analyze complex genomic data efficiently and derive meaningful insights into cancer biology.
> 
> Key features of cBioPortal include:
> 
> Genomic Evolution Visualization: Users can examine the genomic evolution of a patient's cancer through visualizations that display changes in mutation allele frequencies over time. This feature is particularly useful for understanding how cancer evolves and responds to treatment. The Genomic Evolution tab is available for patients with multiple samples, offering visualizations like Line Charts or Heatmaps along with the option to view these changes in the context of the patient's treatment timeline.
> Mutations Tab: This section of cBioPortal provides a detailed view of the mutations identified in each queried gene. Mutations are presented visually along the gene's domain structure, with the mutation frequency at specific sites indicated. This interactive visualization allows users to explore the mutation details further by hovering over or clicking on them.
> Group Comparison: A powerful feature that enables the comparison of mutation frequencies across different groups of interest. Depending on the number of selected groups, the appearance of the plots changes, providing a flexible way to visualize and analyze genetic variations across different cohorts or conditions. Users can customize the plots to focus on specific genes, gene sets, or user-defined gene lists.
> cBioPortal stands out for its user-friendly interface and the depth of its analytical tools, making it an indispensable tool for cancer genomics research. The platform's capabilities in providing detailed mutation analyses, comparing genetic variations across groups, and visualizing genomic evolution over time support a wide range of research activities from basic science to clinical decision-making.
> 
> For more detailed information and tutorials on how to use these and other features of cBioPortal, you can visit the cBioPortal User Guide Overview at https://docs.cbioportal.org/user-guide/overview/.
> 
> 


Example two:
>  Question: How to install cBioportal in docker
> Source Document Type : documentation
> To install cBioPortal using Docker, follow these steps:
> 
> Clone the cBioPortal Docker Compose repository:
> 
> git clone https://github.com/cBioPortal/cbioportal-docker-compose.git
> cd cbioportal-docker-compose
> Initialize the configuration:
> 
> ./init.sh
> Use Docker Compose to start the services:
> 
> docker compose up
> After completing these steps, you should be able to access the cBioPortal website at http://localhost:8080/.
> 
> Additionally, to import studies into cBioPortal, you can use the following command:
> 
> 
> docker compose run cbioportal metaImport.py -u http://cbioportal:8080 -s study/lgg_ucsf_2014/ -o
> To clear persistent data volumes, use:
> 
> 
> docker compose down -v
> For more detailed information, you can refer to the documentation at https://docs.cbioportal.org/deployment/docker/.
