### ISSUE TITLE
Screen Recording Demo Video

### ISSUE THREAD

**Issue by cannin** [cannin/gsoc_2024_cbioportal_chatbot#27]
Make a 30-60s demo video (screen recording no audio) for the README after more of the issues closed.

**Comment by XinlingWang0628** [comment]
Done. Added video in readme.

**Comment by XinlingWang0628** [comment]
Done. 
<img width="897" alt="Screenshot 2024-08-30 at 2 42 20 PM" src="https://github.com/user-attachments/assets/db53c9bd-071e-4f93-81fd-3c980b910c07">
