### ISSUE TITLE
Test GPT Endpoints

### ISSUE THREAD

**Issue by cannin** [cannin/gsoc_2024_cbioportal_chatbot#4]
Check messages for instructions on accessing the GPT endpoint

- [x] Chat completion API
- [x] Embedding API

**Comment by XinlingWang0628** [comment]
gpt4 is compatible with AzureChatOpenAI, but it is incompatible with AzureOpenAIEmbeddings. 
Also tried gpt-35-turbo-instruct for embeddings, but it's incompatible either.
Demo code can run with gpt4 and openai embeddings with openai api key.

Error message for gpt4 AzureOpenAIEmbeddings:

> openai.BadRequestError: Error code: 400 - {'error': {'code': 'OperationNotSupported', 'message': 'The embeddings operation does not work with the specified model, gpt-4. Please choose different model and try again. You can learn more about which models can be used with each operation here: https://go.microsoft.com/fwlink/?linkid=2197993.'}}


Error message for gpt-35-turbo-instruct AzureOpenAIEmbeddings:

> openai.BadRequestError: Error code: 400 - {'error': {'code': 'OperationNotSupported', 'message': 'The embeddings operation does not work with the specified model, gpt-35-turbo-instruct. Please choose different model and try again. You can learn more about which models can be used with each operation here: https://go.microsoft.com/fwlink/?linkid=2197993.'}}
