### ISSUE TITLE
Add Used Documents to Demo

### ISSUE THREAD

**Issue by cannin** [cannin/gsoc_2024_cbioportal_chatbot#5]
A big component the demo is missing is what documents were used to respond. Example:

```
User: How do I install cBioPortal
ChatBot: Happy to help. First download Docker then ... [Source: <a href="https://github.com/cBioPortal/cbioportal/tree/master/docs/deployment/docker/README.md">README.md</a>]
```

**Comment by XinlingWang0628** [comment]
I will make a list of docs which can generate response using retrieved text.

**Comment by XinlingWang0628** [comment]
List: https://docs.google.com/spreadsheets/d/14ptOen4I25JXbSyyPw9smBxlCQU46T-sI78K-yNIi28/edit?usp=sharing 
Done

**Comment by XinlingWang0628** [comment]
Done. 
<img width="1312" alt="Screenshot 2024-08-30 at 2 42 57 PM" src="https://github.com/user-attachments/assets/ae8357c3-5d4b-4a6e-b90f-f763a800a792">
